### ISSUE TITLE
[BUG] V2.0 Auth Flow Error

### ISSUE THREAD

**Issue by editter** [PTST/O365-HomeAssistant#36]
**Describe the bug**
It looks like during the auth flow the account parameter isn't being passed in which is causing validation errors.

**To Reproduce**
1 Setup the component per the instructions
2. Click Link Account
3. After coming back from the Account Linking flow I get redirected to https://[my domain]/api/o365?code=[a guid]&state=[alpha numeric string]
The page conents shows "500 Internal Server Error Server got itself into trouble"
4. Going to the logs I get the following error
```
Log Details (ERROR)
Mon Feb 03 2020 14:34:47 GMT-0600 (Central Standard Time)
Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
resp = await task
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 120, in handle
result = handler(request, **request.match_info)
File "/config/custom_components/o365/__init__.py", line 142, in get
do_setup(self._hass, self.config)
TypeError: do_setup() missing 1 required positional argument: 'account'
```
**Expected behavior**
I get a 200 response or a happy face and the logs are free of errors

**Installation method (please select one):**
- [X] HACS
- [ ] Manual Installation

**Additional context**
- I have the newest version installed as of 2:00 pm CST
- I show the App is linked successfully on the Microsoft side

**Comment by artaxx81** [comment]
Same problem here. After a little bit of troubleshooting I even not getting the authentification notification anymore.

Here my logs:

`Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/o365/sensor.py", line 28, in setup_platform
    is_authenticated = account.is_authenticate
AttributeError: 'Account' object has no attribute 'is_authenticate'`

**Comment by larsteeke** [comment]
Same problem. Deleted the app in the account and tried another one, too. Got error 500 in both cases.

**Comment by PTST** [comment]
I have published [V2.0.1](https://github.com/PTST/O365-HomeAssistant/releases/tag/V2.0.1) which fixes the auth flow.

**Comment by PTST** [comment]
> Same problem here. After a little bit of troubleshooting I even not getting the authentification notification anymore.
> 
> Here my logs:
> 
> `Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 158, in _async_setup_platform await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT) File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for return fut.result() File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/o365/sensor.py", line 28, in setup_platform is_authenticated = account.is_authenticate AttributeError: 'Account' object has no attribute 'is_authenticate'`

This issue was also fixed in v2.0.1

**Comment by artaxx81** [comment]
Is there any chance to reauthenticate? I deleted the plugin, deleted the Azure app, deleted the configuration.

I get my calendars as entities but when I want to use them I still get an error 500.

**Comment by PTST** [comment]
What do you mean by "when I want to use them"

**Comment by artaxx81** [comment]
I tried to get a visual calender with this lovelace card:
https://github.com/ljmerza/calendar-card

Or do I get something wrong?

At the end of the day I want to use calendar entries like "HOLIDAY" for doing some automations.

At the moment I am getting:
```
data_str_repr: []
data: 
event_active: false
friendly_name: Entsorgungskalender
```

and as state

`False`

**Comment by PTST** [comment]
It will in its current state not work with any of the calendar cards, i am working on supporting either something like [atomic_calendar](https://github.com/atomic7777/atomic_calendar) or creating my own calendar card for this. But that's gonna take a while. So for now this integration is currently only intended for automations.

The state of the calendar entity is set to True/False depending on whether you currently have an active event in you calendar.

Your entity attributes seems to be empty. Do you have any calendar events today?

Have you set the offsets in your configuration.yaml entry? if not the calendar entity will only look for events in the next 24h period

**Comment by artaxx81** [comment]
Ah, deleting the o365token led to a new authentication and now I am getting a True an some informations with my test event.

Now I have to learn how to deal with the payload. I hoped that I do not have to learn that because I do not understand it.

Thank you very much for your help, now the plugin is working as expected.
